services:
  db:
    image: mirror.gcr.io/library/postgres:15-alpine
    container_name: erp_db_container
    environment:
      - POSTGRES_DB=global_erp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/create_global_erp.sql:/docker-entrypoint-initdb.d/create_global_erp.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: erp_backend_container
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erp_frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_BASE_PATH=/

volumes:
  postgres_data: